test/cuelang:
  image: nixery.dev/shell/gnumake/findutils/cue
  script:
    - cd schemas/cuelang
    - make test

test/graphql:
  # Missing /usr/bin/env
  #image: nixery.dev/shell/gnumake/findutils/nodejs
  image: node:11
  script:
    - cd schemas/graphql
    - make deps
    - make test
