test/cuelang:
  image: nixery.dev/shell/gnumake/findutils/cue
  script:
    - cd schemas/cuelang
    - make test

test/graphql:
  image: nixery.dev/shell/gnumake/findutils/nodejs
  script:
    - cd schemas/graphql
    - make deps
    - make test
